/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfigurasi.DBkoneksi;

/**
 *
 * @author user
 */
public class FrmDataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form FrmDataMahasiswa
     * 
     */
    private DefaultTableModel DftTblModel_mahasiswa;
    private String SQL;
    public FrmDataMahasiswa() {
        initComponents();
    }
    
    public void TampilData(){
        DftTblModel_mahasiswa = new DefaultTableModel();
        DftTblModel_mahasiswa.addColumn("NIM");
        DftTblModel_mahasiswa.addColumn("NAMA");
        DftTblModel_mahasiswa.addColumn("PROGRAM STUDI");
        jTable_mhs.setModel(DftTblModel_mahasiswa);
        java.sql.Connection conn = new DBkoneksi().connect();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from tmhs";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()){
                DftTblModel_mahasiswa.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("NAMA"),
                    res.getString("PRODI")
                });
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_nim = new javax.swing.JTextField();
        jTextField_nama = new javax.swing.JTextField();
        jComboBox_prodi = new javax.swing.JComboBox<>();
        jButton_add = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mhs = new javax.swing.JTable();
        jButton_keluar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_cari = new javax.swing.JTextField();
        jComboBox_kategoripencarian = new javax.swing.JComboBox<>();
        jButton_cari_ok = new javax.swing.JButton();
        jButton_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM DATA MASTER MAHASISWA");

        jLabel2.setText("NIM");

        jLabel3.setText("NAMA");

        jLabel4.setText("PRODI");

        jTextField_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nimActionPerformed(evt);
            }
        });

        jComboBox_prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEKNIK INFORMATIKA", "SISTEM INFORMASI", "KOMPUTER AKUNTASI" }));

        jButton_add.setText("Add New");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_deleteMouseClicked(evt);
            }
        });
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jTable_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_mhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_mhs);

        jButton_keluar.setText("Keluar");
        jButton_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_keluarMouseClicked(evt);
            }
        });

        jLabel5.setText("CARI");

        jTextField_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cariActionPerformed(evt);
            }
        });

        jComboBox_kategoripencarian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAMA", "NIM" }));

        jButton_cari_ok.setText("OK");
        jButton_cari_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cari_okActionPerformed(evt);
            }
        });

        jButton_refresh.setText("Refresh");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_keluar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton_add)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_save)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_update)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_delete))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton_cari_ok)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton_refresh))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jComboBox_kategoripencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_save)
                    .addComponent(jButton_update)
                    .addComponent(jButton_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_kategoripencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cari_ok)
                    .addComponent(jButton_refresh))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton_keluar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        jTextField_nim.setText("");
        jTextField_nama.setText("");
        jComboBox_prodi.setSelectedItem("PILIH :");
        jTextField_nim.requestFocus();
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTextField_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nimActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        TampilData();
    }//GEN-LAST:event_formWindowActivated

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = new DBkoneksi().connect();
        try {
            java.sql.PreparedStatement stmt = conn.prepareStatement("insert into tmhs (nim,nama,prodi)values(?,?,?)");
            try {
                stmt.setString(1, jTextField_nim.getText());
                stmt.setString(2, jTextField_nama.getText());
                stmt.setString(3, jComboBox_prodi.getSelectedItem().toString());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil disimpan","pesan",JOptionPane.INFORMATION_MESSAGE);
                TampilData();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "data gagal disimpan","pesan",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jTable_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_mhsMouseClicked
        // TODO add your handling code here:
        int baris = jTable_mhs.getSelectedRow();
        jTextField_nim.setText(DftTblModel_mahasiswa.getValueAt(baris, 0).toString());
        jTextField_nama.setText(DftTblModel_mahasiswa.getValueAt(baris, 1).toString());
        jComboBox_prodi.setSelectedItem(DftTblModel_mahasiswa.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_jTable_mhsMouseClicked

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = new DBkoneksi().connect();
        try {
            java.sql.PreparedStatement stmt = conn.prepareStatement("update tmhs set nama =?,prodi=? where nim = ?");
            try {
                stmt.setString(1, jTextField_nama.getText());
                stmt.setString(2, jComboBox_prodi.getSelectedItem().toString());
                stmt.setString(3, jTextField_nim.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"data berhasil di update","pesan",JOptionPane.INFORMATION_MESSAGE);
                TampilData();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal di update","pesan",JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (HeadlessException | SQLException e) {
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_deleteMouseClicked
        // TODO add your handling code here:
        java.sql.Connection conn = new DBkoneksi().connect();
        int ok = JOptionPane.showConfirmDialog(null, "apakah anda yakin menghapus data ?","konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            try {
            SQL = "delete from tmhs where nim =' "+jTextField_nim.getText()+"'";
            java.sql.PreparedStatement stmt = conn.prepareStatement(SQL);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil di hapus");
            TampilData();
            jTextField_nim.setText("");
            jTextField_nama.setText("");
            jComboBox_prodi.setSelectedItem("PILIH :");
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "gagal di hapus");
       }
        }
    }//GEN-LAST:event_jButton_deleteMouseClicked

    private void jButton_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_keluarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_keluarMouseClicked

    private void jButton_cari_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cari_okActionPerformed
        // TODO add your handling code here:
        DftTblModel_mahasiswa = new DefaultTableModel();
        DftTblModel_mahasiswa.addColumn("NIM");
        DftTblModel_mahasiswa.addColumn("NAMA");
        DftTblModel_mahasiswa.addColumn("PROGRAM STUDI");
        jTable_mhs.setModel(DftTblModel_mahasiswa);
        java.sql.Connection conn = new DBkoneksi().connect();
        try {
            java.sql.Statement stmt = conn.createStatement();
            if (jComboBox_kategoripencarian.getSelectedItem().equals("NIM")) {
                SQL = "select * from tmhs where nim like '%"+jTextField_cari.getText()+"%'";
                
            } else if(jComboBox_kategoripencarian.getSelectedItem().equals("NAMA")){
                SQL = "select * from tmhs where nama like '%"+jTextField_cari.getText()+"%'";
            }
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_mahasiswa.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("NAMA"),
                    res.getString("PRODI")
                });
                
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_cari_okActionPerformed

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        // TODO add your handling code here:
        jTextField_cari.setText("");
        TampilData();
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jTextField_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cariActionPerformed

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_cari_ok;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_keluar;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_kategoripencarian;
    private javax.swing.JComboBox<String> jComboBox_prodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mhs;
    private javax.swing.JTextField jTextField_cari;
    private javax.swing.JTextField jTextField_nama;
    private javax.swing.JTextField jTextField_nim;
    // End of variables declaration//GEN-END:variables
}
